export const tally = [
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "Job",
      transaction: "Income",
      accountFrom: "",
      accountTo: "Savings",
      name: "Salary",
    },
    {
      date: "2022-01-01",
      amount: "100.00",
      category: "Hobbies",
      transaction: "Expense",
      accountFrom: "ATM",
      accountTo: "",
      name: "Item Purchase",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "others",
      transaction: "Transfer",
      accountFrom: "ATM",
      accountTo: "Savings",
      name: "daily saving goal",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "Job",
      transaction: "Income",
      accountFrom: "",
      accountTo: "Savings",
      name: "Salary",
    },
    {
      date: "2022-01-01",
      amount: "100.00",
      category: "Hobbies",
      transaction: "Expense",
      accountFrom: "ATM",
      accountTo: "",
      name: "Item Purchase",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "others",
      transaction: "Transfer",
      accountFrom: "ATM",
      accountTo: "Savings",
      name: "daily saving goal",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "Job",
      transaction: "Income",
      accountFrom: "",
      accountTo: "Savings",
      name: "Salary",
    },
    {
      date: "2022-01-01",
      amount: "100.00",
      category: "Hobbies",
      transaction: "Expense",
      accountFrom: "ATM",
      accountTo: "",
      name: "Item Purchase",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "others",
      transaction: "Transfer",
      accountFrom: "ATM",
      accountTo: "Savings",
      name: "daily saving goal",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "Job",
      transaction: "Income",
      accountFrom: "",
      accountTo: "Savings",
      name: "Salary",
    },
    {
      date: "2022-01-01",
      amount: "100.00",
      category: "Hobbies",
      transaction: "Expense",
      accountFrom: "ATM",
      accountTo: "",
      name: "Item Purchase",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "others",
      transaction: "Transfer",
      accountFrom: "ATM",
      accountTo: "Savings",
      name: "daily saving goal",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "Job",
      transaction: "Income",
      accountFrom: "",
      accountTo: "Savings",
      name: "Salary",
    },
    {
      date: "2022-01-01",
      amount: "100.00",
      category: "Hobbies",
      transaction: "Expense",
      accountFrom: "ATM",
      accountTo: "",
      name: "Item Purchase",
    },
    {
      date: "2022-01-01",
      amount: "300.00",
      category: "others",
      transaction: "Transfer",
      accountFrom: "ATM",
      accountTo: "Savings",
      name: "daily saving goal",
    },
  ];

  export const accounts = [
    {
      startBalance: "5,000,000.00",
      currBalance:  "5,000,000.00",
      type: "Savings",
      account: "Chinabank",
      accCode: "CBC",
      number: "1234567890",
    },
    {
      startBalance: "5,000,000.00",
      currBalance:  "5,000,000.00",
      type: "ATM",
      account: "Chinabank",
      accCode: "CBC",
      number: "1234567890",
    },
    {
      startBalance: "5,000,000.00",
      currBalance:  "5,000,000.00",
      type: "ATM",
      account: "Chinabank",
      accCode: "CBC",
      number: "1234567890",
    },
  ];